### ISSUE TITLE
Search Screen Update

### ISSUE THREAD

**Issue by vivek-sam** [vivek-sam/CropNet#1]
Search Screen should look like this..

![image](https://user-images.githubusercontent.com/20189725/38319527-9dacefea-384f-11e8-8cc0-6ace1b322b0f.png)

If search is done without selecting crop or person then both crop and person should be searched. IF crop is selected and searched only crop data should be displayed. Similarly if person is selected only person data is to be displayed.

The display can be a list view for now with a locate on map button which can take us there to the map view.

**Comment by AbilashPais** [comment]
UI is done and backend for search is remaining.
  1 both crop and name together
