### ISSUE TITLE
Profile creation

### ISSUE THREAD

**Issue by vivek-sam** [vivek-sam/CropNet#2]
The screen does not look good.. Here is a reference which can be followed. not the colors but the format.

![image](https://user-images.githubusercontent.com/20189725/38319783-51edb1f6-3850-11e8-9aef-76e414a46a96.png)

**Comment by AbilashPais** [comment]
have done the UI changes. Which has to be reviewed

**Comment by vivek-sam** [comment]
This is how I want the UI to look like...

![image](https://user-images.githubusercontent.com/20189725/38375961-11bc1a9e-3915-11e8-96d6-618c9c14af8c.png)

**Comment by vivek-sam** [comment]
Profile Creation page 3 can look like thi...

![image](https://user-images.githubusercontent.com/20189725/38416924-02c2e2c6-39b4-11e8-86ce-99daecfa1715.png)
