### ISSUE TITLE
Map view requires a list view which can be incorporated as a button on the search 

### ISSUE THREAD

**Issue by vivek-sam** [vivek-sam/CropNet#3]
a button on the search should give the results or change the view to a list instead of map

![image](https://user-images.githubusercontent.com/20189725/38319916-b64bb0b2-3850-11e8-8969-dcef166c7018.png)

**Comment by AbilashPais** [comment]
list view is done

**Comment by vivek-sam** [comment]
Clicking on the list view does not list anything.. is the functionality done ?

**Comment by vivek-sam** [comment]
list view can look like this

![image](https://user-images.githubusercontent.com/20189725/38425617-01e73186-39d2-11e8-96b7-6088e11887c2.png)

**Comment by AbilashPais** [comment]
its been solved
